name: Build CleverCloud

on:
  workflow_run:
    workflows: ["Stages"]
    types:
      - success
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Installer les outils nécessaires
        run: |
          sudo apt update
          sudo apt install -y gpg curl git
          
          curl -fsSL https://clever-tools.clever-cloud.com/gpg/cc-nexus-deb.public.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/cc-nexus-deb.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/cc-nexus-deb.gpg] https://nexus.clever-cloud.com/repository/deb stable main" | sudo tee -a /etc/apt/sources.list
          
          sudo apt-get update
          sudo apt-get install clever-tools

      - name: Créer des fichiers buildés (exemple)
        run: |
          mkdir dist
          echo "Fichier généré lors du build" > dist/build-file.txt

      - name: Sauvegarder les fichiers buildés
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./dist  # Remplace par ton dossier contenant les fichiers buildés
          retention-days: 1
