name: Stages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed  

jobs:
  Build CleverCloud:
  Deploy to CleverCloud:
    needs: Build CleverCloud
  Configure CleverCloud:
    needs: [ Build CleverCloud, Deploy to CleverCloud]